- name: Copy PV scripts/templates
  copy:
    src: "{{ item }}"
    dest: "/tmp"
    mode: 0777
  loop:
    - "create-pvs.sh"
    - "pv.template.yaml"
    - "label-nodes.sh"
  when: redeploy is not defined

- name: Set k8s nodes list based on hostname
  set_fact:
    nodes: "{{ groups[cluster] | join(' ') | quote }}"
  when: node_name is not defined

- name: Set k8s nodes list based on 'node_name' variable (e.g. "-e node_name=ansible_host" to use the node's IP)
  set_fact:
    nodes: "{{ groups[cluster] | map('extract', hostvars, node_name) | join(' ') | quote }}"
  when: node_name is defined

- name: Label nodes
  shell: "CLUSTER={{ cluster }} NODES={{ nodes }} /tmp/label-nodes.sh"
  register: labelout
  changed_when: "'labled' in labelout.stdout"
  when: redeploy is not defined

- name: Create PVs
  shell: "NAMESPACE={{ cluster }} MPATH_SIZE={{ ais_mpath_size }} MPATHS={{ ais_mpaths | join(' ') | quote }} NODES={{ nodes }} /tmp/create-pvs.sh"
  register: createpvsout
  changed_when: "'configured' in createpvsout.stdout or 'created' in createpvsout.stdout"
  when: redeploy is not defined

- name: Copy cluster yaml
  template:
    src: "ais.yaml.j2"
    dest: "/tmp/{{ cluster }}.yaml"
    mode: 0777
    lstrip_blocks: true
  vars:
    cluster: "{{ cluster }}"
    cluster_size: "{{ groups[cluster] | length }}"

- name: Create namespace if it does not exist
  shell: "kubectl create ns {{ cluster }} || true"
  register: namespaceout
  changed_when: "'created' in namespaceout.stdout"

- name: Deploy cluster
  command: "kubectl apply -f /tmp/{{ cluster }}.yaml"
  register: createout
  changed_when: "'configured' in createout.stdout or 'created' in createout.stdout"
