name: Publish ais-k8s release 

on:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"
env:
  AISOPERATOR_IMAGE: 'aistorage/ais-operator'

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.0'
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: make aisoperator image
      run: |
        pushd $GITHUB_WORKSPACE/operator
        IMG="${{ env.AISOPERATOR_IMAGE }}:${{ inputs.version }}" make docker-build docker-push
        popd
    
    - name: make operator yaml file
      run: |
        pushd $GITHUB_WORKSPACE/operator
        VERSION="${{ inputs.version }}" IMG="${{ env.AISOPERATOR_IMAGE }}:${{ inputs.version }}" make bundle-manifests
        popd

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: operator/dist/*
